<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>w</string>
	</array>
	<key>name</key>
	<string>cweb</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(@\*)(\d+)? ([\w ]+.)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.cweb</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.header-depth.cweb</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.section-title.cweb</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^@)</string>
			<key>name</key>
			<string>meta.section.cweb</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex.latex</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\|</string>
					<key>end</key>
					<string>\|</string>
					<key>name</key>
					<string>meta.inline-code.cweb</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.c++</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@&lt;) (.+) (@&gt;=)|(@p)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.cweb</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.block-name.cweb</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.cweb</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.cweb</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=^@\*?)</string>
			<key>name</key>
			<string>meta.block.code.cweb</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>@&lt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.begin.cweb</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>entity.block-reference.name.cweb</string>
					<key>end</key>
					<string>@&gt;;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.end.cweb</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.block-reference.cweb</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^@ </string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.cweb</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^@\*?)</string>
			<key>name</key>
			<string>meta.paragraph.cweb</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex.latex</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\|</string>
					<key>end</key>
					<string>\|</string>
					<key>name</key>
					<string>meta.inline-code.cweb</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.c++</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^@i</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.cweb</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.quoted.other.include.cweb</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.include.cweb</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(@d) (\w+)(?:\(.*?\))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.cweb</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.define.cweb</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cweb</string>
	<key>uuid</key>
	<string>3396B72B-D53B-4EBA-9AF5-D3B98F3C0A43</string>
</dict>
</plist>
